### ISSUE TITLE
Latest doctrine/instantiator bugs out with patchwork

### ISSUE THREAD

**Issue by krodyrobi** [sebastianbergmann/phpunit#2746]
PHPUnit      ^5.7
Instantiator  1.1.0
PHP             7.1
Patchwork    ^2.0
Installation   Composer

Also happens manifests on ^6.2

Small reproducing project
https://github.com/krodyrobi/testing

**Comment by krodyrobi** [comment]
Cross-linking https://github.com/antecedent/patchwork/issues/64

**Comment by sebastianbergmann** [comment]
`phpunit-mock-objects` has a dependency on `doctrine/instantiator`. In `composer.json` it "asks" for the latest version that is backwards compatible with version 1.0.2 (`^1.0.2`).

When you use PHP 7.0 then you get version 1.0.5 of `doctrine/instantiator`. And when you use PHP 7.1 then you get version 1.1.0 of `doctrine/instantiator`.

As far as I am concerned that is the correct behavior.

### PHP 7.0

```
$ php-70 -v
PHP 7.0.23-dev (cli) (built: Jul 26 2017 08:21:10) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
```

```
$ php-70 /usr/local/bin/composer require phpunit/phpunit
Using version ^6.2 for phpunit/phpunit
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 28 installs, 0 updates, 0 removals
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/resource-operations (1.0.0): Loading from cache
  - Installing sebastian/recursion-context (3.0.0): Loading from cache
  - Installing sebastian/object-reflector (1.1.1): Loading from cache
  - Installing sebastian/object-enumerator (3.0.2): Loading from cache
  - Installing sebastian/global-state (2.0.0): Loading from cache
  - Installing sebastian/exporter (3.1.0): Loading from cache
  - Installing sebastian/environment (3.1.0): Loading from cache
  - Installing sebastian/diff (1.4.3): Loading from cache
  - Installing sebastian/comparator (2.0.0): Loading from cache
  - Installing doctrine/instantiator (1.0.5): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/phpunit-mock-objects (4.0.2): Loading from cache
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.2): Loading from cache
  - Installing theseer/tokenizer (1.1.0): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
  - Installing phpunit/php-token-stream (1.4.11): Loading from cache
  - Installing phpunit/php-code-coverage (5.2.1): Loading from cache
  - Installing webmozart/assert (1.2.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (3.2.0): Loading from cache
  - Installing phpspec/prophecy (v1.7.0): Loading from cache
  - Installing phar-io/version (1.0.1): Loading from cache
  - Installing phar-io/manifest (1.0.1): Loading from cache
  - Installing myclabs/deep-copy (1.6.1): Loading from cache
  - Installing phpunit/phpunit (6.2.3): Loading from cache
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.3)
phpunit/phpunit suggests installing phpunit/php-invoker (^1.1)
phpunit/phpunit suggests installing ext-xdebug (*)
Writing lock file
Generating autoload files
```

### PHP 7.1

```
$ php-71 -v
PHP 7.1.9-dev (cli) (built: Jul 26 2017 08:24:43) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

```
$ php-71 /usr/local/bin/composer require phpunit/phpunit
Using version ^6.2 for phpunit/phpunit
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 28 installs, 0 updates, 0 removals
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/resource-operations (1.0.0): Loading from cache
  - Installing sebastian/recursion-context (3.0.0): Loading from cache
  - Installing sebastian/object-reflector (1.1.1): Loading from cache
  - Installing sebastian/object-enumerator (3.0.2): Loading from cache
  - Installing sebastian/global-state (2.0.0): Loading from cache
  - Installing sebastian/exporter (3.1.0): Loading from cache
  - Installing sebastian/environment (3.1.0): Loading from cache
  - Installing sebastian/diff (1.4.3): Loading from cache
  - Installing sebastian/comparator (2.0.0): Loading from cache
  - Installing doctrine/instantiator (1.1.0): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/phpunit-mock-objects (4.0.2): Loading from cache
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.2): Loading from cache
  - Installing theseer/tokenizer (1.1.0): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
  - Installing phpunit/php-token-stream (1.4.11): Loading from cache
  - Installing phpunit/php-code-coverage (5.2.1): Loading from cache
  - Installing webmozart/assert (1.2.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (3.2.0): Loading from cache
  - Installing phpspec/prophecy (v1.7.0): Loading from cache
  - Installing phar-io/version (1.0.1): Loading from cache
  - Installing phar-io/manifest (1.0.1): Loading from cache
  - Installing myclabs/deep-copy (1.6.1): Loading from cache
  - Installing phpunit/phpunit (6.2.3): Loading from cache
sebastian/global-state suggests installing ext-uopz (*)
phpunit/phpunit suggests installing phpunit/php-invoker (^1.1)
Writing lock file
Generating autoload files
```

Also see what @Danack wrote in https://github.com/sebastianbergmann/phpunit-mock-objects/pull/370#issuecomment-317999031.

**Comment by sebastianbergmann** [comment]
I apologize for closing this with an inappropriate explanation (https://github.com/sebastianbergmann/phpunit/issues/2746#issuecomment-318292785). I did not look (closely enough) at the report and assumed that it was yet another Composer-related non-issue with regards to the 1.1.0 release of doctrine/instantiator.

Anyway, I do not think that there is an issue here for PHPUnit. Looks like something related to doctrine/instantiator or antecedent/patchwork. Maybe @Ocramius as the maintainer of doctrine/instantiator can provide some insight here?

**Comment by Ocramius** [comment]
This is normal: instantiator 1.1 requires PHP 7.1. we clarify it here: http://doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html

**Comment by sebastianbergmann** [comment]
@Ocramius This is about the "PHP Fatal error:  A void function must not return a value in vendor/doctrine/instantiator/src/Doctrine/Instantiator/Instantiator.php on line 149" error the original poster is getting (see https://github.com/krodyrobi/testing/blob/master/README.md).

**Comment by Ocramius** [comment]
There's no return statement in that method:
https://github.com/doctrine/instantiator/blob/185b8868aa9bf7159f5f953ed5afb2d7fcdc3bda/src/Doctrine/Instantiator/Instantiator.php#L148-L167

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by krodyrobi** [comment]
There is no issue when patchwork is not loaded, doctrine as is works and is fetched properly, it may just be a doctrine / patchwork issue. Wasn't sure so I've added the issue on both repos.
Thank you for the quick replies :D !

**Comment by Ocramius** [comment]
@krodyrobi can you please link all related issues here, for future readers?

**Comment by krodyrobi** [comment]
If there is anything important to add, I'll manually add them here as well.
I've linked the threads with patchwork so technically if someone has a similar issue they could follow there as well.

**Comment by antecedent** [comment]
It's Patchwork that attempts to add the `return` statement. I'll be working on a quick fix.

**Comment by antecedent** [comment]
Version 2.0.8 (available now) should fix that.

Please note that `void`-typed functions and methods will not be redefinable until next version.

A PHAR will be available soon.

**Comment by antecedent** [comment]
Special thanks to @krodyrobi for the exemplary bug report!

**Comment by krodyrobi** [comment]
Thank you all for actively maintaining awesome projects :D !
Edited the description with the new fix and added the zip instead of a link for historical reasons.

**Comment by Rarst** [comment]
@antecedent I am still having issues _with_ Patchwork 2.0.8, lowering Instantiator version down to 1.0.5 makes them go away. Is there a Patchwork issue I should report in or create one?

**Comment by krodyrobi** [comment]
https://github.com/antecedent/patchwork/issues/64
