### ISSUE TITLE
ErrorException: unserialize(): Error at offset 0  in AbstractPhpProcess.php

### ISSUE THREAD

**Issue by BonBonSlick** [sebastianbergmann/phpunit#3141]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.1
| PHP version         | 7.2
| Installation Method | Composer

from vendor packages installed with composer.

```
PHPUnit\Framework\Exception: Doctrine\Common\Collections\ArrayCollection {#480
  -elements: []
}


Caused by
ErrorException: unserialize(): Error at offset 0 of 68 bytes in /var/www/site/vendor/phpunit/phpunit/src/Util/PHP/AbstractPhpProcess.php:247
Stack trace:

#0 [internal function]: PHPUnit\Util\PHP\AbstractPhpProcess->PHPUnit\Util\PHP\{closure}(8, 'unserialize(): ...', '/var/www/site...', 247, Array)

#1 /var/www/site/vendor/phpunit/phpunit/src/Util/PHP/AbstractPhpProcess.php(247): unserialize('Doctrine\\Common...')
```

for 

```
  public function AuthenticationForm_WithValidCredentials_Submit(string $url) : void
    {
        $client = static::createClient([], ['HTTPS' => true]);
        $crawler = $client->request('GET', $url);
        $form = $crawler->filter('form')->form();
        $credentials = ['email' => 'admin@email.com', 'password' => 'admin'];
        $client->submit($form, $credentials);
        $client->followRedirect();
        $this->assertSame(Response::HTTP_OK, $client->getResponse()->getStatusCode());
    }
```

It was working on PhPUnit 6 i think, so before upgrade

Configs
```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="./vendor/phpunit/phpunit/phpunit.xsd"
         backupGlobals="false"
         colors="true"
         bootstrap="./vendor/autoload.php"
         backupStaticAttributes="false"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         beStrictAboutTestsThatDoNotTestAnything="true"
         beStrictAboutCoversAnnotation="true"
         beStrictAboutOutputDuringTests="true"
         verbose="true"
         beStrictAboutChangesToGlobalState="true"
         beStrictAboutTodoAnnotatedTests="true"
         stopOnError="false"
         stopOnIncomplete="false"
         stopOnSkipped="false"
         stopOnRisky="false"

         processIsolation="true"

         stopOnFailure="false">
```

Without processIsolation we got

```
Doctrine\Common\Collections\ArrayCollection {#5735
  -elements: []
}
```

And that is it, result of test

I am not sure is it doctrine, some settings, symfony or PhPUnit, i missed time when some changes were made and broke it. Other tests are passed well. 

Thanks for help.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by BonBonSlick** [comment]
That was from our side. Issue can be closed. Thank you.

**Comment by matzora** [comment]
Hi guys. I have the same problem.

@BonBonSlick What's the modification you've done to do it works ?

Thanks !

**Comment by dertin** [comment]
Hello, the same thing is happening to me. Soon I share more information.

**Comment by dertin** [comment]
Hi, I share my test.

**Test code**:
```
public function testPrint()
    {

        try {
            ob_start();

            // Configuration request with POST parameters a = 1, b = 2
            // https://www.site.com/index/htmlPrint
            $objRequestIndex = new Core\Request('index/htmlPrint', 'POST', array('a'=>1,'b'=>2));

            // Execute the Request, simulate the execution of a web request to the configured Request
            Core\Bootstrap::run($objRequestIndex);

            $htmlIndex = ob_get_clean(); // HTML code

            // Fail if errors HTML
            if ($htmlIndex != strip_tags($htmlIndex)) {
                  $this->assertTrue(true, 'OK');
            } else {
                  $this->fail('Not HTML');
            }
        } catch (\Exception $e) {
            $this->fail('Exception: '.$e->getMessage());
        }
    }
```
**Code that I want to test**:
I notice that if you have a exit() statement in the code that print the html this cause an error.
```
    private function generateHTMLOutput()
    {
        echo '<!DOCTYPE html><html lang="es" dir="ltr" itemscope="itemscope" itemtype="http://schema.org/WebPage"><head><meta charset="UTF-8"><title>Test</title></head><body><div class="wrapper"><p>Hello</p></div></body></html>';
        exit(); // CAUSE THE ERROR
    }

    public function htmlPrint()
    {
        $this->generateHTMLOutput();
    }
```

**ERROR**:
```
There was 1 error:

1) Particle\Apps\Test\TestingControllerTest::testPrint
PHPUnit\Framework\Exception: <!DOCTYPE html><html lang="es" dir="ltr" itemscope="itemscope" itemtype="http://schema.org/WebPage"><head><meta charset="UTF-8"><title>Test</title></head><body><div class="wrapper"><p>Hello</p></div></body></html>

Caused by
ErrorException: unserialize(): Error at offset 0 of 213 bytes in phar:///usr/local/bin/phpunit/phpunit/Util/PHP/AbstractPhpProcess.php:247
Stack trace:
#0 [internal function]: PHPUnit\Util\PHP\AbstractPhpProcess->PHPUnit\Util\PHP\{closure}(8, 'unserialize(): ...', 'phar:///usr/loc...', 247, Array)
#1 phar:///usr/local/bin/phpunit/phpunit/Util/PHP/AbstractPhpProcess.php(247): unserialize('<!DOCTYPE html>...')
#2 phar:///usr/local/bin/phpunit/phpunit/Util/PHP/AbstractPhpProcess.php(171): PHPUnit\Util\PHP\AbstractPhpProcess->processChildResult(Object(Particle\Apps\Test\TestingControllerTest), Object(PHPUnit\Framework\TestResult), '<!DOCTYPE html>...', '')
#3 phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php(803): PHPUnit\Util\PHP\AbstractPhpProcess->runTestJob('<?php\nuse PHPUn...', Object(Particle\Apps\Test\TestingControllerTest), Object(PHPUnit\Framework\TestResult))
#4 phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php(776): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#5 phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php(776): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#6 phar:///usr/local/bin/phpunit/phpunit/TextUI/TestRunner.php(566): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php(203): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#8 phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php(156): PHPUnit\TextUI\Command->run(Array, true)
#9 /usr/local/bin/phpunit(589): PHPUnit\TextUI\Command::main()
#10 {main}
ERRORS!
```

Versions:
```
PHP 7.2.3 (cli) (built: Mar 21 2018 15:48:12) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.3, Copyright (c) 1999-2018, by Zend Technologies

PHPUnit 7.1.2 by Sebastian Bergmann and contributors.
```

**Comment by linslin** [comment]
@BonBonSlick how did you fix it?

**Comment by linslin** [comment]
OK finally we found the problem. While the error message `
ErrorException: unserialize(): Error at offset...` seemed to point a problem in PHPUnit code. The problem over here was that the assertion we used was wrong / failed. The test itself did run but the assertion failed. So in our case our test first looked like this (Laravel 4.2):

    /**
     * A basic functional test example.
     * @runInSeparateProcess
     */
    public function test302Redirect()
    {
        //enable filters
        \Route::enableFilters();

        $this->call(
            'GET',
            'http://my-application/highscores'
        );

        $this->assertEquals(302, $this->client->getResponse()->getStatusCode());
    }

But status code we recived was `301` - so we fixed this:

    /**
     * A basic functional test example.
     * @runInSeparateProcess
     */
    public function test301Redirect()
    {
        //enable filters
        \Route::enableFilters();

        $this->call(
            'GET',
            'http://my-application/highscores'
        );

        $this->assertEquals(301, $this->client->getResponse()->getStatusCode());
    }

Finally the error message went away. Unfortunately, when running `@runInSeparateProcess` PHPUnit seems not recognizing the correct error message thrown by the assertion we used. Instead this ends up in a PHP error.

I hope this will help others. Take a look at your tests and ensure the assertions are valid.

**Comment by BonBonSlick** [comment]
@linslin problems mostly because of your code. It is not related to phpunit. You are doing something wrong, i do not remmber already how solved it, but it was not phpunit issue. 

> That was from our side. I

**Comment by friggingee** [comment]
I just stumbled upon this thread searching for "phpunit errorexception unserialize error at offset 0" as one of the few results.

For me the solution was to disable XDebug since it polluted the output of php when phpunit was running its tests.  
Same thing seems to be the case with the original author's problem where you can see in the stack trace that it begins with `unserialize('Doctrine\\Common...')` which is definitely not valid serialized data.

I was scratching my head over this ticket and comment chain since it sounded unlikely that phpunit would just fail this hard on an unexpected return value because it should just mark the test as failed in this case.

The actual issue seems to be either polluted php output or uncaught exceptions in the code which is being tested.

**Comment by armanist** [comment]
Any dd(), dump(), var_dump(), print_r() of these functions called in your test case will throw that error exception now...
is this intentional?

**Comment by f-giftagram** [comment]
in my case, this is what I have in that test case, note its not even the first test case in that there are several others before that works but this one

```
/**
     * @test
     */
    public function it_responds_with_200_if_there_are_no_associationss() {
        dd('mhgvjhgvkh');
    }
```
And I still get that error. Really dont know what to do. The tests is existing test I cannot remove it.

**Comment by f-giftagram** [comment]
> in my case, this is what I have in that test case, note its not even the first test case in that there are several others before that works but this one
> 
> ```
> /**
>      * @test
>      */
>     public function it_responds_with_200_if_there_are_no_associationss() {
>         dd('mhgvjhgvkh');
>     }
> ```
> 
> And I still get that error. Really dont know what to do. The tests is existing test I cannot remove it. (I intentionally removed the actual content of the test and reduced to just a dd)

Holy cow!!!! There happens to be a missing migration digging further. It was a painful digging tho. So instead of just erroring out as usual I'm met with that error that tells me nothing but cause PTSD. Glad I was able to figure this out. So like something said earlier, its likely something in the code it may just be too hard or painful to find.
